"""Update User

Revision ID: 197a79388282
Revises: a0625610e5f8
Create Date: 2022-05-16 01:11:01.997483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197a79388282'
down_revision = 'a0625610e5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
